use yt-dlp

diff --git a/.github/workflows/yt_playlist.yml b/.github/workflows/yt_playlist.yml
--- a/.github/workflows/yt_playlist.yml
+++ b/.github/workflows/yt_playlist.yml
@@ -19,17 +19,16 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y jq
-        sudo apt-get install -y youtube-dl
+        sudo apt-get install -y curl
+        sudo curl -L https://yt-dlp.org/downloads/latest/yt-dlp -o /usr/local/bin/yt-dlp
+        sudo chmod a+rx /usr/local/bin/yt-dlp
         sudo apt-get install -y gh
-
-    - name: Update youtube-dl
-      run: sudo youtube-dl -U
 
     - name: Extract video URLs from playlist
       id: extract_links
       run: |
         # Extract video URLs from playlist
-        youtube-dl -j --flat-playlist "${{ github.event.inputs.playlist_url }}" | jq -r '.id' | sed 's_^_https://www.youtube.com/watch?v=_' > links.txt
+        yt-dlp -j --flat-playlist "${{ github.event.inputs.playlist_url }}" | jq -r '.id' | sed 's_^_https://www.youtube.com/watch?v=_' > links.txt
         echo "Extracted Links:"
         cat links.txt
 
@@ -42,7 +41,7 @@ jobs:
         touch results/all_videos.txt
 
         while read -r link; do
-          youtube-dl -o 'metadata/%(id)s.%(ext)s' --write-info-json "$link" || echo "Failed to download metadata for $link" >> results/errors.txt
+          yt-dlp -o 'metadata/%(id)s.%(ext)s' --write-info-json "$link" || echo "Failed to download metadata for $link" >> results/errors.txt
         done < links.txt
 
         # Extract titles and descriptions, filter those with links in descriptions
@@ -50,9 +49,10 @@ jobs:
           if [ -f "$file" ]; then
             title=$(jq -r '.title' "$file")
             description=$(jq -r '.description' "$file")
-            echo -e "Title: $title\nDescription: $description\nURL: ${file%.info.json}\n" >> results/all_videos.txt
+            video_url="https://www.youtube.com/watch?v=$(jq -r '.id' "$file")"
+            echo -e "Title: $title\nDescription: $description\nURL: $video_url\n" >> results/all_videos.txt
             if echo "$description" | grep -q -E 'http[s]?://[^ ]+'; then
-              echo -e "Title: $title\nDescription: $description\nURL: ${file%.info.json}\n" >> results/with_links.txt
+              echo -e "Title: $title\nDescription: $description\nURL: $video_url\n" >> results/with_links.txt
             fi
           else
             echo "Missing metadata for file: $file" >> results/errors.txt
@@ -75,7 +75,7 @@ jobs:
         path: results/with_links.txt
 
     - name: Upload error log
-      if: failure()
+      if: always()
       uses: actions/upload-artifact@v3
       with:
         name: errors
